version: 1.0.{build}
image: Visual Studio 2017
before_build:
  - nuget restor
  
build:
  publish_wap: true
  verbosity: minimal
test_script:
- cmd: vstest.console /logger:Appveyor <assembly> PapapaGo.Tests
